### ISSUE TITLE
[bug] Wallet Connect on some devices only shows QrCode option

### ISSUE THREAD

**Issue by r29taheri** [tmm/wagmi#686] opened 2022-07-09 13:07 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.4.3

### Current Behavior

on most devices works fine but on some iPhone devices shows only Qr option.
what it shows:
![image](https://user-images.githubusercontent.com/24974629/178107003-7506496b-89c8-4225-89d4-f966f064da19.png)

### Expected Behavior

![image](https://user-images.githubusercontent.com/24974629/178107008-c090a741-aaa7-4b3c-a86c-d05b8466db89.png)

### Steps To Reproduce

1. Open Wallet Connect on iPhone device
2. for some devices only shows QrCode option

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://0.4.x.wagmi.sh/examples/connect-wallet

### Anything else?

Also tested on [0.4.x example](https://0.4.x.wagmi.sh/examples/connect-wallet) and [latest version example](https://wagmi.sh/examples/connect-wallet) and it's same

**Comment by tmm** [comment] 2022-07-09 17:23
I tried reproducing this on the 0.4.x docs site using iOS 15.5, but wasn't able to (duplicate of https://github.com/tmm/wagmi/issues/360). This is likely an issue with WalletConnect's device detection. Please create a minimal reproducible example using CodeSandbox and re-open this issue.

**Closed by tmm** 2022-07-09 17:23 UTC

**Comment by rvmelkonian** [comment] 2022-07-09 19:50
I am also having this issue. Just recording a screen recording of what happens during the flow

**Comment by r29taheri** [comment] 2022-07-10 10:23
Hey @tmm, thanks for your response and sorry for replying late, unfortunately I am also not able to reproduce it as it happens only in some iPhones.
here is a video recorded from iPhone 11 Pro, iOS 15.5

works fine on [Walletconnect example](https://example.walletconnect.org/) but doesn't work on [Wagmi example](https://wagmi.sh/examples/connect-wallet)

https://user-images.githubusercontent.com/24974629/178140907-40eb759d-6e62-4884-a9b7-9fbde0886327.mp4

let me know if you need any other information.
thanks in advance

**Comment by r29taheri** [comment] 2022-07-13 15:51
we found the issue, it was about **walletconnect/ethereum-provider** latest update, we downgraded it to 1.7.1 and it works fine now.
