### ISSUE TITLE
[bug] build with Nextjs, error 'Uncaught SyntaxError: Unexpected template string' occurs 

### ISSUE THREAD

**Issue by liran319** [tmm/wagmi#211] opened 2022-02-23 05:25 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.2.15

### Demo repo:
https://github.com/liran319/next-wagmi-demo

I have install `wagmi@0.2.15` into my project with Nextjs, it works well when start project with 'yarn dev'.
But `Uncaught SyntaxError: Unexpected template string` occurs when run 'yarn build && yarn start'.
<img width="418" alt="image" src="https://user-images.githubusercontent.com/4019372/155265349-b5238362-5305-49b7-959c-7048634b4e01.png">

It seems that only occurs on production mode.And there is no stack to debug.
Could you please have a check?

### Expected Behavior

Both development and production mode work well.

### Steps To Reproduce

1. Clone the repo `https://github.com/liran319/next-wagmi-demo`, and enter that folder;
2. Run `yarn` to install deps;
3. Run 'yarn build && yarn start'
4. check console, found 'Uncaught SyntaxError: Unexpected template string', and button doesn't work

**Comment by o-az** [comment] 2022-02-23 15:44
A possible solution: can you try removing `swcMinify` setting in your `next.config.js` file? I had the same issue that went away when I removed `swcMinify` setting.
![CleanShot 2022-02-23 at 09 42 04](https://user-images.githubusercontent.com/23618431/155353663-4ced2c41-c1d7-45d0-a4a7-345b4051e9d4.png)

**Comment by liran319** [comment] 2022-02-23 16:08
> 

OH yes, it is! It works! 
But I think there is some where can be optimized and fixed on `wagmi`.

Thanks you very much!

**Comment by csadai** [comment] 2022-03-05 09:50
Maybe related: I just upgraded to `0.2.15` and the app won't launch.
The error message `Unhandled Runtime Error
SyntaxError: Unexpected private name #switchChain. Cannot parse class method with private name.`

My `swcMinify` is at `false`. 
If I remove the `WalletConnectConnector` from my connectors, it works. There really seems to be a problem there.

**Comment by tmm** [comment] 2022-03-05 15:31
What version of JavaScript are you targeting? (If you are using TypeScript, it's the `target` field in `tsconfig.json`.)

**Comment by cnasc** [comment] 2022-03-07 21:07
Also on Next (12.1.0), using `wagmi@0.2.17`. Found a similar issue with failures only happening in prod builds. Minimal reproduction is just importing `Provider` from wagmi.

In this case the message I get is:
`TypeError: Cannot read properties of undefined (reading 'map')` in Chromium and `TypeError: i is undefined` in Firefox. Unfortunately can't tell the context from the linked minified code.

I've tried going back a few versions (0.2.13 and 0.2.10) because it sounded like this worked for people on Next in the past, but same result there.

**Comment by tmm** [comment] 2022-03-07 23:53
@cnasc I just upgraded the wagmi docs site to `next@12.1.0` and `wagmi@0.2.18` with no build problems.

**Comment by liran319** [comment] 2022-03-08 05:07
> What version of JavaScript are you targeting? (If you are using TypeScript, it's the `target` field in `tsconfig.json`.)

Hi there,

https://github.com/liran319/next-wagmi-demo/blob/main/tsconfig.json
You can check the version in this repo here.

**Comment by cnasc** [comment] 2022-03-08 13:19
> @cnasc I just upgraded the wagmi docs site to `next@12.1.0` and `wagmi@0.2.18` with no build problems.

:thinking: odd. Tried `0.2.18` just in case but same result. Looking at the docs site source, I don't see any difference in build config or anything. I copied https://github.com/tmm/wagmi/blob/main/docs/components/core/Providers.tsx directly just in case there was something wrong with the way I'd written it myself, but no difference.

Will have to dig deeper into the Next side of things to figure it out I think

**Comment by tmm** [comment] 2022-03-29 13:59
@liran319 can you try with the latest version `0.2.22`?

**Comment by cnasc** [comment] 2022-03-29 14:19
> can you try with the latest version `0.2.22`?

On my end, `0.2.22` no longer breaks in a prod build on my app (when just importing `Provider`). Awesome to see, going to try integrating fully this week

**Comment by csadai** [comment] 2022-03-29 14:31
Mine still breaks on Safari (version 14.1.2). It fails on this Webkit line https://github.com/WebKit/webkit/blob/main/Source/JavaScriptCore/parser/Parser.cpp#L884 

Exact error: 
```
Unhandled Runtime Error
SyntaxError: Unexpected private name #switchChain. Cannot parse class method with private name.
Call Stack
eval

[native code]
./node_modules/wagmi-core/connectors/walletConnect/dist/wagmi-core-connectors-walletConnect.esm.js
```

My set up:
```json
"wagmi": {
      "version": "0.2.22",
      "resolved": "https://registry.npmjs.org/wagmi/-/wagmi-0.2.22.tgz",
      "integrity": "sha512-WtpRO/JGTIrcs9vBdIJZe...",
      "requires": {
        "@ethersproject/providers": "^5.5.1",
        "@walletconnect/ethereum-provider": "1.7.5",
        "wagmi-core": "0.1.16",
        "walletlink": "^2.5.0"
      }
    },
```

Note: If I remove WalletConnect from my config, it works. 

```javascript
new WalletConnectConnector({
      options: {
        infuraId,
        qrcode: true,
      },
    }),
```

**Comment by tmm** [comment] 2022-03-31 03:03
@csadai can you try now?

**Comment by csadai** [comment] 2022-03-31 07:23
Hi @tmm Sorry I didn't sync my comment from #288. It works indeed, thanks a lot for fixing.

**Comment by tmm** [comment] 2022-04-04 01:50
@liran319 this appears to be an issue with next's SWC minification. You can add feedback to this discussion https://github.com/vercel/next.js/discussions/30237

the other issue brought up in the thread is related to es6 private fields. that is now fixed.

**Closed by tmm** 2022-04-04 01:50 UTC
