### ISSUE TITLE
[bug]  Connecting to MetaMask (injected wallet) from Chrome Extension.

### ISSUE THREAD

**Issue by jamalavedra** [tmm/wagmi#419] opened 2022-05-06 12:44 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.3.3

### Current Behavior
Injected wallet is not available from the popup.

<img width="385" alt="Screenshot 2022-05-06 at 14 41 50" src="https://user-images.githubusercontent.com/22459423/167133349-2c4c5290-4c17-496a-b11f-0d06c1f1b292.png">

### Steps To Reproduce

Use any boilerplate like https://github.com/aeksco/react-typescript-web-extension-starter and try to connect with metamask from the popup

**Comment by tmm** [comment] 2022-05-06 13:38
From some quick research, it looks like injected wallets might not have great support for Chrome Extensions since they inject into the browser `window`, not necessarily the extension `window`. You could try creating your own `Connector` and using [`chrome.windows`](https://developer.chrome.com/docs/extensions/reference/windows/). This seems out of scope for this library, but if you create a minimal reproducible example I can try to take a look.

**Closed by tmm** 2022-05-06 13:38 UTC

**Comment by jamalavedra** [comment] 2022-05-07 12:31
Here's a reproducible example I just created:

https://github.com/jamalavedra/wagmi-browser-extension

You'll see the injected wallet isn't working.

**Comment by tmm** [comment] 2022-05-07 15:10
Thanks for providing that! Can you add some info on how to run the example?

**Comment by jamalavedra** [comment] 2022-05-07 16:44
np!
Just `yarn` to install all dependencies and `yarn watch` to build it.
Then, go to manage extensions, `brave://extensions/` in Brave, and `LoadUpacked` after enabling developer mode.
