### ISSUE TITLE
[bug] Disconnect not persisting and reconnecting on page load

### ISSUE THREAD

**Issue by sammdec** [tmm/wagmi#38] opened 2022-01-06 12:03 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.0.17

### Current Behavior

Using a Next.js app, Im calling the `disconnect` function from the `useAccount` hook. It does disconnect but then after refreshing the page it reconnects again and the account info re-populates

### Expected Behavior

I would expect to be disconnected from ym wallet so that I may be able to reconnect again with a different wallet or simply use the site in its disconnected state

### Steps To Reproduce

1. Connect via InjectedConnector -> useAccount becomes populated with data and useConnect returns `connected:true`. 
2. Press disconnect button which calls the `disconnect` function. -> useAccount returns empty data as expected and `connected: false`. 
3. Refresh the page
4. usAccount becomes populated with data again and `connected:true`

**Edit**: It seems as though if I remove `autoConnect` prop on the provider then it does indeed keep me disconnected however that then means on every refresh I need to reconnect. Ideally I would like connect automatically until I explicitly call disconnect

**Comment by iDuuck** [comment] 2022-01-06 14:01
Seems like a this is a duplicate of #35 (as you noticed yourself in the "Edit").

---

**For the solution:** It normally should not prompt every time to connect again through MetaMask, since the connecting only needs to be established once. Could be an option in MetaMask? For me it is only asking once.

**Comment by sammdec** [comment] 2022-01-06 14:06
I would expect though that if I call disconnect after reloading it should ask me to connect again and not assume I want to automatically connect with the last used account

**Comment by iDuuck** [comment] 2022-01-06 14:46
I thought it would work with autoConnect? This is a little misleading for you I think. 
Having disconnected programatically is like visiting the page, without having connected in the first place. So, if the Provider sees `autoConnect` it will automatically search for the shim that was injected by Metamask, and try to connect.

If you want the desired behavior, you might want to implement ur own local storage, which is checking whether the user disconnected once in it's lifetime and set the autoConnect prop based on this local storage.

**Comment by tmm** [comment] 2022-01-06 15:34
@sammdec MM (and other injected providers) don't support programmatically disconnecting.

I agree it's confusing to reconnect on page reload, but technically it's the most accurate since the account is still connected to the browser. (wagmi does handle disconnect events coming from connector directly. For example, disconnecting in MM UI.)

That said, you could manage connection status separately in the browser, but you would need to listen and handle different connection events (i.e. disconnecting or switching account directly through MM extensions).

**Closed by tmm** 2022-01-06 15:34 UTC

**Comment by sammdec** [comment] 2022-01-06 20:45
Ah ok yeah that makes sense! Happy to stick what the most default behaviour is in that case
